#
# Define which script to run according to os family
#
- include: miscellaneous-debian.yml
  when: ansible_os_family == 'Debian'

- include: miscellaneous-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Ensure proper bash history size and format
  lineinfile:
    line={{ item }}
    dest=/etc/profile.d/99-bash_history.sh
    create=yes
  with_items:
    - export HISTTIMEFORMAT="{{ bash_history_format }}"
    - export HISTFILESIZE={{ bash_history_size }}

- name: Ensure less command can read all charset
  lineinfile:
    line={{ item }}
    dest=/etc/profile.d/99-less.sh
    create=yes
  with_items:
    - export LESSCHARSET=utf-8
